### PR TITLE
Fix memory leaks

### PR DESCRIPTION
**Pull request by buger**
It was happening because of time goroutine, and timer was not stopping as well. 

Binaries:
https://www.dropbox.com/s/0gd9tnf3qw7ieeo/gor_fix_memory_leaks_x64.tar.gz?dl=1
https://www.dropbox.com/s/nvrakek2vm42pnk/gor_fix_memory_leaks_x86.tar.gz?dl=1

### CODE REVIEW

**Comment by chunacatsunflower** [comment]
wow, that was fast!  I'll push it up to our server tomorrow and check it out.

**Comment by Kooper** [comment]
Hello,

I tried the provided binary from https://www.dropbox.com/s/0gd9tnf3qw7ieeo/gor_fix_memory_leaks_x64.tar.gz?dl=1 and it still leaks. On my load it's 1.7 Gb in 3 minutes:

```PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND```
```12281 root      20   0 3173m 1.7g 3204 S  115  5.4   3:36.19 gor```

**Comment by buger** [comment]
It took a bit longer, but result is great :)

Number of spawned goroutines dropped in order of magnitude, and it should work way more stable and faster. 

/cc @chunacatsunflower @Kooper thanks for the feedback! (binaries are updated)

**Comment by Kooper** [comment]
@buger, the new version has awesome performance indeed! It is even much faster then 0.9.8 - truly amazing. I'm able to replicate up to 800 RPS of HTTP traffic from raw socket (approx. 2MB/s of incoming traffic) without significant CPU load. Thank you for this!

Memory leak, however is not fixed completely. With the input volume I have a 100MB/hour increase in memory consumption:
```
  PID USER      PR  NI  VIRT  RES  SHR S %CPU %MEM    TIME+  COMMAND            
21507 root      20   0 1349m 838m 1808 S   79  2.7 294:44.68 gor
```

**Comment by buger** [comment]
@Kooper this PR https://github.com/buger/gor/pull/201 should fix rest of memory leaks :)

**Comment by buger** [comment]
Released in https://github.com/buger/gor/releases/tag/v0.10.1

**Pull request merged**
