### PR TITLE
Really read bytes up to the size of the buffer

### PR DESCRIPTION
**Pull request by gallir**
The c.conn.Read() doesn't necesarily read all bytes up to the size
of the buffer. When the response is larger than the buffer the
Dialer doesn't close the connection and it becomes corrupted so
the later traffic is discarded and never reaches the servers.

### CODE REVIEW

**Comment by salimane** [comment]
@gallir  thanks for the PR.

Please could you add a test case for this and rebase your branch against master.

Thanks

**Comment by buger** [comment]
While it is true that it does not read all the bytes, it have protection for corruption on the line 183 https://github.com/buger/gor/pull/247/files#diff-f374d958f214bda94cf6f66191e13362R183

If it sees that buffer is full, it just reconnects. This is for sure not the most efficient way, but at least it should not fail.

**Comment by gallir** [comment]
@buger 

That doesn't protect anything for incomplete buffers because if a partial response smaller than the buffer size is read that function is not going to disconnect and it's assumed that everything was read and then the following connections will be corrupted. That's what I tried to explain in the PR:

"Dialer doesn't close the connection and it becomes corrupted so
the later traffic is discarded and never reaches the servers."

**Comment by buger** [comment]
I see, I was under the assumption that it should always fill all the buffer. Do you know if it's possible to simulate this somehow? This change is tricky, so we definitely need some tests. Thank you! I will think how to add them as well.

**Comment by buger** [comment]
Fixed in #277

**Pull request closed without merging**
