### PR TITLE
Make TCPOutput more robust to failures

### PR DESCRIPTION
**Pull request by wmoss**
This should allow for running a gor listener on a
production box and bringing up and down the replay
node without having to go restart the listener.

### CODE REVIEW

**Comment by wmoss** [comment]
Hey @buger it doesn't seem like the tests are running successfully on master at the moment (even without my change). Do you have any idea what's up?

**Comment by buger** [comment]
@wmoss looks like travis changed smth on their side, and not use `gvm` anymore.

**Comment by buger** [comment]
```go
func (o *TCPOutput) worker() {
	conn, err := o.connect(o.address)
	for ; err != nil; conn, err = o.connect(o.address) {
		time.Sleep(2 * time.Second)
	}

	defer conn.Close()

	for {
		_, err := conn.Write(<-o.buf)
		if err != nil {
			log.Println("Worker failed on write, exitings and starting new worker")
			go o.worker()
			break
		}
	}
}
```

**Comment by buger** [comment]
Looks good to me, thanks! 

Pls also add log call wen you failed connect to replay server. 

Test runner fixed in master, feel free to merge latest master to your branch, and see if tests pass.

**Comment by wmoss** [comment]
Rebased on top of your master and looks like the tests pass. Also, regarding the log line, I'm happy to add one to my new code, but there is [already one in the `connect` method](https://github.com/buger/gor/pull/138/files#diff-c465110e7d4d8911cefe178eb9fd96dcR69), so something is printed out to the terminal on failure to connect. Let me know what you prefer.

**Comment by buger** [comment]
@wmoss ah, i see. Then looks good to me :+1:

**Pull request merged**
