### PR TITLE
Feature flag

### PR DESCRIPTION
**Pull request by ghost**
-timeout flap to support stopping the gortool after n seconds.

### CODE REVIEW

**Comment by buger** [comment]
Hello! This is a nice feature, and I would love to merge it. However, there are few changes I would like you to make:

* Put flag definition to settings.go and Settings object. Instead of `flag.Int` use `flag.DurationVar`. This will allow you to specify duration with units: 1s, 30m, 2h etc.
* We already have http timeout option, and it is not really timeout, make sense rename it to: `exit-delay` or `exit-after`.

**Comment by ortz** [comment]
Hey @buger, thank for the quick response.
I've modified the code and pushed the changes.

Thanks,

**Comment by buger** [comment]
Do you know why pull requests created from "ghost" user?:)

**Comment by ortz** [comment]
Yes, I forked and created the PR with my old user, after I realized that I transferred the repository and closed the old account.
This "ghost" is a deleted user, I guess every user closed user in Github is a ghost.

**Comment by buger** [comment]
Merged, thank you!

**Comment by ortz** [comment]
Great, thanks! waiting for the next release :)

**Comment by buger** [comment]
New version [v0.15.0](https://github.com/buger/gor/releases/tag/v0.15.0) include this features. Thanks!

**Pull request merged**
