### PR TITLE
libpcap based input

### PR DESCRIPTION
**Pull request by dt**

### CODE REVIEW

**Comment by buger** [comment]
Thank you! However i see at as additional engine to input_raw plugin, for mac it will use pcap by default. If you do not mind, i will use your codebase to refactor input raw for support multiple engines.

**Comment by dt** [comment]
Two things: 

1) this isn't quite ready yet -- there's a bug in determining incoming I still need to fix.

2) I started with it in raw but ended up pulling it out into its own input since it has different usage considerations: you must specify _an interface_ to listen on (vs the usual address or just port) and from what I understand, pcap has very different performance characteristics.




I looked at just using the "any" interface to handle bare ":port" listen specs but it reportedly doesn't work on OS X (or can give you unusable, non-Ethernet packets?).




Another issue I still need to dig into is that it looks like maybe it isn't emitting requests made on connections that existed before it started listening (I suspect the TCP assembler) -- I see all my testing requests but when I run it in production it initially sees very low qps that rises over time.



—

**Comment by buger** [comment]
I see thanks! Continue with your investigations them. I did not have too
much free time now anyway, will back to this PR in a few weeks then :)

On Friday, September 11, 2015, David Taylor <notifications@github.com>
wrote:

> Two things:
>
> 1) this isn't quite ready yet -- there's a bug in determining incoming I
> still need to fix.
>
> 2) I started with it in raw but ended up pulling it out into its own input
> since it has different usage considerations: you must specify _an
> interface_ to listen on (vs the usual address or just port) and from what I
> understand, pcap has very different performance characteristics.
>
>
>
>
> I looked at just using the "any" interface to handle bare ":port" listen
> specs but it reportedly doesn't work on OS X (or can give you unusable,
> non-Ethernet packets?).
>
>
>
>
> Another issue I still need to dig into is that it looks like maybe it
> isn't emitting requests made on connections that existed before it started
> listening (I suspect the TCP assembler) -- I see all my testing requests
> but when I run it in production it initially sees very low qps that rises
> over time.
>
>
>
> —
> Sent from Mailbox
>
> On Fri, Sep 11, 2015 at 6:19 AM, Leonid Bugaev <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Thank you! However i see at as additional engine to input_raw plugin,
> for mac it will use pcap by default. If you do not mind, i will use your
> codebase to refactor input raw for support multiple engines.
> > ---
> > Reply to this email directly or view it on GitHub:
> > https://github.com/buger/gor/pull/206#issuecomment-139543910
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/buger/gor/pull/206#issuecomment-139593308>.
>


-- 
Sincerely yours Leonid Bugaev
leonsbox@gmail.com
http:// <http://buger.github.com>leonsbox.com

**Comment by dt** [comment]
It looks like I'm not going to have a chance to dig further into this right away, so i'm not sure if you want to close it or leave it open in case someone else decides to pick it up.

**Comment by buger** [comment]
I see, anyway thank you a lot for your work! 

Priority of this functionality may change because of bugs like this https://github.com/buger/gor/issues/207

**Pull request closed without merging**
