### PR TITLE
Middleware for custom request rewrite logic

### PR DESCRIPTION
**Pull request by buger**
### Middleware
Middleware is a program that accepts request and response payload at STDIN and emits modified requests at STDOUT. You can implement any custom logic like stripping private data, advanced rewriting, support for oAuth and etc.

```
                   Original request      +--------------+
+-------------+----------STDIN---------->+              |
|  Gor input  |                          |  Middleware  |
+-------------+----------STDIN---------->+              |
                   Original response     +------+---+---+
                                                |   ^
+-------------+    Modified request             v   |
| Gor output  +<---------STDOUT-----------------+   |
+-----+-------+                                     |
      |                                             |
      |            Replayed response                |
      +------------------STDIN----------------->----+
```

Middleware can be written in any language, see `examples/middleware` folder for examples.
Middleware program should accept the fact that all communication with Gor is asynchronous, there is no guarantee that original request and response messages will come one after each other. Your app should take care of the state if logic depends on original or replayed response, see `examples/middleware/token_modifier.go` as example.

Simple bash echo middleware (returns same request) will look like this:
```bash
while read line; do
  echo $line
end
```

Middleware can be enabled using `--middleware` option, by specifying path to executable file:
```
gor --input-raw :80 --middleware "/opt/middleware_executable" --output-http "http://staging.server"
```

#### Communication protocol
All messages should be hex encoded, new line character specifieds the end of the message, eg. new message per line.

Decoded payload consist of 2 parts: header and HTTP payload, separated by new line character.  

Example request payload:

```
1 932079936fa4306fc308d67588178d17d823647c 1439818823587396305
GET /a HTTP/1.1
Host: 127.0.0.1

```

Example response payload:

```
2 8e091765ae902fef8a2b7d9dd960e9d52222bd8c 2782013
HTTP/1.1 200 OK
Date: Mon, 17 Aug 2015 13:40:23 GMT
Content-Length: 0
Content-Type: text/plain; charset=utf-8

```

Header contains request meta information separated by spaces. First value is payload type, possible values: `1` - request, `2` - original response, `3` - replayed response.
Next goes request id: unique among all requests (sha1 of time and Ack), but remain same for original and replayed response, so you can create associations between request and responses. Third argument varies depending on payload type: for request - start time, for responses - round-trip time.

HTTP payload is unmodified HTTP requests/responses intercepted from network. You can read more about request format [here](http://www.jmarshall.com/easy/http/), [here](https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol) and [here](http://www.w3.org/Protocols/rfc2616/rfc2616.html). You can operate with payload as you want, add headers, change path, and etc. Basically you just editing a string, just ensure that it is RCF compliant.

At the end modified (or untouched) request should be emitted back to STDOUT, keeping original header, and hex-encoded. If you want to filter request, just not send it. Emitting responses back is optional, and does not affect anything at the moment.

#### Advanced example
Imagine that you have auth system that randomly generate access tokens, which used later for accessing secure content. Since there is no pre-defined token value, naive approach without middleware (or if middleware use only request payloads) will fail, because replayed server have own tokens, not synced with origin. To fix this, our middleware should take in account responses of replayed and origin server, store `originalToken -> replayedToken` aliases and rewrite all requests using this token to use replayed alias. See `examples/middleware/token_modifier.go` and `middleware_test.go#TestTokenMiddleware` as example of described scheme.

Latest precompiled binaries:
https://www.dropbox.com/s/27chmbsqxrolvz4/gor_0.9.9_middleware_x64.tar.gz?dl=1
https://www.dropbox.com/s/vmeg5sexcleoo2e/gor_0.9.9_middleware_x86.tar.gz?dl=1

### CODE REVIEW

**Comment by buger** [comment]
Thanks to https://github.com/buger/gor/pull/160 we how have access to raw response output.

**Comment by alexjurkiewicz** [comment]
Hi, this work looks really interesting! I currently rewrite JSON data by dumping to a file and editing certain fields with sed :D. This looks more robust, hope it lands soon.

**Comment by buger** [comment]
@alexjurkiewicz moreover it allows you to read both original and replayed response, and allow to implement complex stuff like oAuth (rewriting tokens), and much more.

**Comment by buger** [comment]
@alexjurkiewicz now i have working version, any testing and feedback invaluable. Read pull request PR for documentation and see examples and specs. Links to binaries included into PR description as well. Thanks!

**Comment by dt** [comment]
This is really exciting!

Including round-trip-time in the response might be interesting -- at first glance, that is the only thing currently preventing me from converting my current diff reporter (http://github.com/dt/diffmirror) over to be a middleware rather than making its own requests.

**Comment by buger** [comment]
@dt not yet, but thats what i'm working on now

**Comment by buger** [comment]
@dt added response round-trip time, see docs and latest binaries in PR description.

**Comment by buger** [comment]
@dt added handling of connection errors, and timeouts. It use non standard http codes for that, based on CloudFlare protocol. If there is any problem with connection, you get response with status "521", if response read/write timeout "524".

**Comment by lovewhll** [comment]
Latest precompiled binaries does not work.

error info:
panic: reflect: Call using int as type time.Duration

**Comment by buger** [comment]
@lovewhll files updated, try now

**Comment by lovewhll** [comment]
Hi buger,

gor saves requests to file,it works well, but then gor reads from file and replay them, 
it got the error info like this: Failed to decode input payload encoding/hex: odd length hex string 29

the content of requests file just have payload type 1-request .

Any ideas what I might be doing wrong?

Thanks

**Comment by buger** [comment]
@lovewhll well actually in this PR file format have changed (now human readable), so there should not be such issue. Most likely you are using different Gor version, and it sounds like your bug should be fixed in 0.9.8

**Comment by lovewhll** [comment]
Hi buger,

the error (Failed to decode input payload encoding/hex) happens to --middleware.
If remove middleware, it works well. 
so I think it is a new issue.


the details:
 From: File input: /usr/local/project/gor/requests.gor
Failed to decode input payload encoding/hex: odd length hex string 29
[DEBUG][PID 10099][1440022709679642639][117.314076ms] [MIDDLEWARE-MASTER] Received:
[DEBUG][PID 10099][1440022709679802882][0.160243ms] [EMITTER] input:
Failed to decode input payload encoding/hex: odd length hex string 41
[DEBUG][PID 10099][1440022712886536082][3206.733200ms] [MIDDLEWARE-MASTER] Received:
Failed to decode input payload encoding/hex: invalid byte: U+001B 86
[DEBUG][PID 10099][1440022712886615015][0.078933ms] [MIDDLEWARE-MASTER] Received:
Failed to decode input payload encoding/hex: odd length hex string 79
[DEBUG][PID 10099][1440022712886666161][0.051146ms] [MIDDLEWARE-MASTER] Received:
Failed to decode input payload encoding/hex: invalid byte: U+0077 'w' 48
[DEBUG][PID 10099][1440022712886716222][0.050061ms] [MIDDLEWARE-MASTER] Received:
Failed to decode input payload encoding/hex: odd length hex string 11
[DEBUG][PID 10099][1440022712886750988][0.034766ms] [MIDDLEWARE-MASTER] Received:
Failed to decode input payload encoding/hex: odd length hex string 29
[DEBUG][PID 10099][1440022712886776842][0.025854ms] [MIDDLEWARE-MASTER] Received:
Failed to decode input payload encoding/hex: invalid byte: U+006A 'j' 42
[DEBUG][PID 10099][1440022712886805542][0.028700ms] [MIDDLEWARE-MASTER] Received:
Failed to decode input payload encoding/hex: invalid byte: U+0077 'w' 30
[DEBUG][PID 10099][1440022712886833817][0.012076ms] [MIDDLEWARE-MASTER] Received:
[DEBUG][PID 10099][1440022712886821741][0.016199ms] [EMITTER] input:
[DEBUG][PID 10099][1440022712886895059][0.061242ms] [EMITTER] input:
[DEBUG][PID 10099][1440022712886915304][0.020245ms] [EMITTER] input:
[DEBUG][PID 10099][1440022712886935415][0.020111ms] [EMITTER] input:
[DEBUG][PID 10099][1440022712886953420][0.018005ms] [EMITTER] input:

**Comment by buger** [comment]
@lovewhll Thanks! Can you clarify which middleware did you used?

**Comment by lovewhll** [comment]
Hi buger,

My middleware is written in java.
It can accept request at STDIN well.





Thanks

**Comment by buger** [comment]
@lovewhll ensure that requests emitted to STDOUT properly hex encoded, if you will still have issues after that, sharing your middleware code may help.

**Comment by lovewhll** [comment]
Hi buger,

The middleware is just a echo program.

the code: 

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

import org.apache.commons.io.IOUtils;

public class Echo {

	public static void main(String[] args) {
		if(args != null){
			for(String arg : args){
				System.out.println(arg);
			}
			
		}
		
		BufferedReader stdin = new BufferedReader(new InputStreamReader(
				System.in));
		String line = null;

		try {
			while ((line = stdin.readLine()) != null) {
				
				System.out.println(line);
				
			}
		} catch (IOException e) {
			IOUtils.closeQuietly(stdin);
		}
	}

}

**Comment by lovewhll** [comment]
Hi buger,

I`d never seen  2 - original response. Is this a problem?


Thanks

**Comment by buger** [comment]
@lovewhll can you also show how you run gor with middleware (which inputs/outputs do you use), maybe issue happens with specific combinations of plugins.

**Comment by lovewhll** [comment]
Hi buger,

/usr/local/project/gor/gor -verbose=true -debug=true  --output-http-stats=true -stats=true  --input-file /usr/local/project/gor/requests.gor   --middleware "/usr/local/project/gor/gor-echo.sh" --output-http "http://192.168.0.10:8090"

gor-echo.sh
#!/bin/sh
/usr/java/jdk1.7.0_72/bin/java -jar /usr/local/project/gor/gor-echo.jar 


Thanks

**Comment by buger** [comment]
@lovewhll since new file format is human readable, can you ensure that responses included into "requests.gor" file?

**Comment by buger** [comment]
(and how you generated requests.gor file)

**Comment by lovewhll** [comment]
Hi buger,

/usr/local/project/gor/gor --input-raw :8090 --output-file /usr/local/project/gor/requests.gor

Thanks

**Comment by lovewhll** [comment]
Hi buger,

I use examples/middleware/echo_modifier.sh to run gor with middleware,it works well.
so the java middleware is the point.

What is the default charcter code?

Thanks

**Comment by buger** [comment]
@lovewhll should be utf

**Comment by arothian** [comment]
This looks great! The token_modifier example is pretty much the use case I have for this. Hope to try it out soon.

**Comment by buger** [comment]
@lovewhll i just tested your middleware and it worked great (i included it into examples folder). I included java into my Docker development image, and you can test it using `make drun-2`, which basically does: `gor --input-file="./fixtures/requests.gor" --output-dummy=0 --verbose --debug --middleware "java -cp ./examples/middleware echo"`

**Comment by lovewhll** [comment]
@buger it works well, thank you!

**Pull request merged**
